package karaev_jsoup;

/**
 *
 * @author SABIT_KARAEV
 */
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Стоимость криптовалют");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage(getClass().getResource("icon.png")));
        setMinimumSize(new java.awt.Dimension(590, 432));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Стоимость криптовалют на сегодня:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 410, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Биткойн - Bitcoin");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 80, 230, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 80, 140, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Узнать стоимость");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 440, 390, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 150, 140, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 220, 140, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 290, 140, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Эфириум - Ethereum");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 150, 230, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Рипл - XRP");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 220, 230, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("EOS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 290, 230, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("Лайткоин - Litecoin");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 350, 230, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(380, 350, 140, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/karaev_jsoup/bitcoin.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 70, 60, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/karaev_jsoup/ethereum.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 140, 44, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/karaev_jsoup/ripple.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 210, 50, 60);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/karaev_jsoup/eos.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 280, 50, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/karaev_jsoup/litecoin.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 340, 60, 50);

        setSize(new java.awt.Dimension(581, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            jLabel3.setText(getPrice("bitcoin"));
            jLabel4.setText(getPrice("ethereum"));
            jLabel5.setText(getPrice("ripple"));
            jLabel6.setText(getPrice("eos"));
            jLabel11.setText(getPrice("litecoin"));
        } catch (Exception e) {
            System.out.println("Error!");
        }    
    }//GEN-LAST:event_jButton1ActionPerformed
    public String getPrice(String url) throws IOException {
            String BASE_URL = "https://ru.investing.com/crypto/" + url; 
            Document doc = Jsoup.connect(BASE_URL).timeout(5000).get();
            Elements bitcoinPrice = doc.select("span#last_last"); // 
            return(bitcoinPrice.text() + " USD");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
